# Generated by Django 5.2.6 on 2025-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fname',
            field=models.CharField(max_length=255, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lname',
            field=models.CharField(max_length=255, verbose_name='Lastname'),
        ),
    ]
