# Generated by Django 5.2.6 on 2025-09-16 23:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='insensitive_unique_language', violation_error_message='Language already exists'),
        ),
    ]
